### ISSUE TITLE
cargo run --release panicked on Windows 10

### ISSUE THREAD

**Issue by loryhndol** [niklaskorz/linon#2]
Thanks for your great work!

When running `cargo run --release`  , I saw a window popped out and then closed quickly.
And then I got the following message:
```
PS H:\linon> cargo run --release RUST_BACKTRACE=1
    Finished release [optimized] target(s) in 0.20s
     Running `target\release\linon.exe RUST_BACKTRACE=1`
Watching shader main_view.wgsl for changes
thread 'main' panicked at 'A timeout was encountered while trying to acquire the next frame', src\main.rs:118:25
error: process didn't exit successfully: `target\release\linon.exe RUST_BACKTRACE=1` (exit code: 101)
```

Full backtrace:
```
PS H:\linon> cargo run --release        
    Finished release [optimized] target(s) in 0.19s
     Running `target\release\linon.exe`
Watching shader main_view.wgsl for changes
thread 'main' panicked at 'A timeout was encountered while trying to acquire the next frame', src\main.rs:118:25
stack backtrace:
   0:     0x7ff62b5187e2 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff62b5187e2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff62b5187e2 - std::sys_common::backtrace::_print_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff62b5187e2 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff62b53192b - core::fmt::write
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\fmt\mod.rs:1202
   5:     0x7ff62b513fba - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\io\mod.rs:1679
   6:     0x7ff62b51af04 - std::sys_common::backtrace::_print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff62b51af04 - std::sys_common::backtrace::print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff62b51af04 - std::panicking::default_hook::closure$1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:295
   9:     0x7ff62b51ab3a - std::panicking::default_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:314
  10:     0x7ff62b51b6f1 - std::panicking::rust_panic_with_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:698
  11:     0x7ff62b51b5fd - std::panicking::begin_panic_handler::closure$0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:588
  12:     0x7ff62b51920f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:138        
  13:     0x7ff62b51b2c0 - std::panicking::begin_panic_handler
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
  14:     0x7ff62b5613f5 - core::panicking::panic_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
  15:     0x7ff62afbb7a7 - core::ptr::drop_in_place<smallvec::IntoIter<[wgpu_hal::vulkan::TextureView; 1]>>::h42248b4d02eb71b7       
  16:     0x7ff62afbd4cd - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}::h026373da4c9537f1      
  17:     0x7ff62af921fc - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::heeda87ad31a3e9f8
  18:     0x7ff62afbf28f - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::register_window::h97b9195762a165de  19:     0x7ff62afbdb3c - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::send_event::hb65f51a129b384f0     
  20:     0x7ff62af9c416 - winit::platform_impl::platform::event_loop::public_window_callback_inner::{{closure}}::h3cc58a117d20e92f  
  21:     0x7ff62afbdf7e - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind::h285897d818c1367c   
  22:     0x7ff62aff0781 - winit::platform_impl::platform::event_loop::public_window_callback::h449f2ab3a7e2a068
  23:     0x7fffec5be858 - CallWindowProcW
  24:     0x7fffec5be4ee - CallWindowProcW
  25:     0x7fffcb44f0f0 - glPushClientAttrib
  26:     0x7fffec5be858 - CallWindowProcW
  27:     0x7fffec5be3dc - DispatchMessageW
  28:     0x7fffec5d0c03 - SendMessageTimeoutW
  29:     0x7fffecb90ef4 - KiUserCallbackDispatcher
  30:     0x7fffea931704 - NtUserDispatchMessage
  31:     0x7fffec5be2ea - DispatchMessageW
  32:     0x7ff62b245400 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::owned_windows::h4806490af10ade3f
  33:     0x7ff62b23e155 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3fcace8632a37903
  34:     0x7ff62b24510e - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind::hbe105054c71cd984   
  35:     0x7ff62b239f77 - winit::platform_impl::platform::event_loop::process_control_flow::h0a35e58fe4e373a4
  36:     0x7fffec5be858 - CallWindowProcW
  37:     0x7fffec5be3dc - DispatchMessageW
  38:     0x7fffec5d0c03 - SendMessageTimeoutW
  39:     0x7fffecb90ef4 - KiUserCallbackDispatcher
  40:     0x7fffea931704 - NtUserDispatchMessage
  41:     0x7fffec5be2ea - DispatchMessageW
  42:     0x7ff62aff0394 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h16e7cc5f56750b1b
  43:     0x7ff62afaab92 - alloc::alloc::box_free::h6e50a91b56d03608
  44:     0x7ff62afae0b1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf36c1bfa1e55cdc2     
  45:     0x7ff62afcc415 - std::thread::local::LocalKey<T>::with::h03f409ca0290ae68
  46:     0x7ff62aff8d2e - linon::start_watcher::h02739b06691b190e
  47:     0x7ff62afe7d26 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3e8d1794eee0fa9f
  48:     0x7ff62b042fec - std::rt::lang_start::{{closure}}::h46b119017c6dfaa6
  49:     0x7ff62b50f3ce - core::ops::function::impls::impl$2::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:283
  50:     0x7ff62b50f3ce - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  51:     0x7ff62b50f3ce - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  52:     0x7ff62b50f3ce - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  53:     0x7ff62b50f3ce - std::rt::lang_start_internal::closure$2
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  54:     0x7ff62b50f3ce - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  55:     0x7ff62b50f3ce - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  56:     0x7ff62b50f3ce - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  57:     0x7ff62b50f3ce - std::rt::lang_start_internal
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  58:     0x7ff62aff914c - main
  59:     0x7ff62b53a5dc - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  60:     0x7ff62b53a5dc - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  61:     0x7fffec7674b4 - BaseThreadInitThunk
  62:     0x7fffecb426a1 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\linon.exe` (exit code: 101)
```

**Comment by niklaskorz** [comment]
Sorry for not getting back on this, is this still the case with the latest version?

**Comment by loryhndol** [comment]
Sorry but yes, it still panicked on my computer. BTW, the compiler version is `rustc 1.69.0 (84c898d65 2023-04-16)`
